create table "users" (
    "id" bigint primary key generated by default as identity,
    "name" varchar not null unique,
    "password_hash" varchar not null
);
create table "images" (
    "id" bigint primary key generated by default as identity,
    "format" varchar not null,
    "title" varchar not null,
    "author" bigint not null,
    "timestamp" timestamptz not null,
    constraint "fk_author" foreign key ("author") references "users" ("id")
);
create table "images_votes" (
    "image_id" bigint,
    "user_id" bigint,
    "upvote" boolean not null,
    primary key ("image_id", "user_id"),
    constraint "fk_image_id" foreign key ("image_id") references "images" ("id"),
    constraint "fk_user_id" foreign key ("user_id") references "users" ("id")
);
create index "idx_images_author" on "images" ("author");
create index "idx_images_timestamp" on "images" ("timestamp");
create index "idx_images_votes_image_id" on "images_votes" ("image_id");
create index "idx_images_votes_user_id" on "images_votes" ("user_id");